export const tutor = [
  {
    id: 2344556,
    name: "Tanya",
    qualification: "Bachelor's in Education",
    experience: 5,
    specialization: ["Mathematics"],
    currentlyWorking: true,
  },
  {
    id: 234455789,
    name: "Jane Smith",
    qualification: "Master's in Education",
    experience: 3,
    specialization: "Science",
    currentlyWorking: false,
  },
  {
    id: 234458685,
    name: "Alice Johnson",
    qualification: "Ph.D. in Physics",
    experience: 5,
    specialization: ["Physics", "Mathematics"],
    currentlyWorking: true,
  },
  {
    id: 23445090,
    name: "Bob Miller",
    qualification: "Bachelor's in English Literature",
    experience: 3,
    specialization: ["English", "History"],
    currentlyWorking: true,
  },
  {
    id: 23445454,
    name: "Eva Davis",
    qualification: "Master's in Chemistry",
    experience: 1,
    specialization: ["Chemistry", "Biology"],
    currentlyWorking: false,
  },
  {
    id: 23445576,
    name: "Sarah White",
    qualification: "Bachelor's in History",
    experience: 3,
    specialization: ["History", "Social Studies"],
    currentlyWorking: true,
  },
  {
    id: 23445565,
    name: "Michael Brown",
    qualification: "Ph.D. in Mathematics",
    experience: 5,
    specialization: ["Mathematics", "Computer Science"],
    currentlyWorking: true,
  },
  {
    id: 23445758,
    name: "Emily Taylor",
    qualification: "Master's in English Language",
    experience: 5,
    specialization: ["English", "Literature"],
    currentlyWorking: false,
  },
  {
    id: 2344567,
    name: "David Turner",
    qualification: "Bachelor's in Biology",
    experience: 2,
    specialization: ["Biology", "Chemistry"],
    currentlyWorking: true,
  },
  {
    id: 2344598,
    name: "Olivia Harris",
    qualification: "Master's in Social Studies",
    experience: 3,
    specialization: ["Social Studies", "History"],
    currentlyWorking: false,
  },
  {
    id: 2344509,
    name: "Andrew Clark",
    qualification: "Ph.D. in Computer Science",
    experience: 6,
    specialization: ["Computer Science", "Mathematics"],
    currentlyWorking: true,
  },
  {
    id: 2344534,
    name: "Sophie Turner",
    qualification: "Bachelor's in Physics",
    experience: 4,
    specialization: ["Physics", "Mathematics"],
    currentlyWorking: false,
  },
  {
    id: 23445534,
    name: "William Johnson",
    qualification: "Master's in Literature",
    experience: 4,
    specialization: ["Literature", "English"],
    currentlyWorking: true,
  },
  {
    id: 2344576,
    name: "Grace Davis",
    qualification: "Bachelor's in Chemistry",
    experience: 2,
    specialization: ["Chemistry", "Biology"],
    currentlyWorking: true,
  },
  {
    id: 2344551,
    name: "Daniel White",
    qualification: "Ph.D. in History",
    experience: 6,
    specialization: ["History", "Social Studies"],
    currentlyWorking: false,
  },
  {
    id: 2344552,
    name: "Emma Miller",
    qualification: "Master's in Mathematics",
    experience: 8,
    specialization: ["Mathematics", "Physics"],
    currentlyWorking: true,
  },
  {
    id: 2344553,
    name: "Aiden Taylor",
    qualification: "Bachelor's in English Language",
    experience: 1,
    specialization: ["English", "Literature"],
    currentlyWorking: false,
  },
  {
    id: 2344554,
    name: "Mia Turner",
    qualification: "Master's in Biology",
    experience: 7,
    specialization: ["Biology", "Chemistry"],
    currentlyWorking: true,
  },
  {
    id: 2344555,
    name: "James Harris",
    qualification: "Ph.D. in Social Studies",
    experience: 5,
    specialization: ["Social Studies", "History"],
    currentlyWorking: true,
  },
  {
    id: 2344559,
    name: "Lily Clark",
    qualification: "Bachelor's in Computer Science",
    experience: 3,
    specialization: ["Computer Science", "Mathematics"],
    currentlyWorking: false,
  },
  {
    id: 2344558,
    name: "Ryan Turner",
    qualification: "Master's in Geography",
    experience: 6,
    specialization: ["Geography", "Social Studies"],
    currentlyWorking: true,
  },
  {
    id: 2344550,
    name: "Sophia Miller",
    qualification: "Ph.D. in Economics",
    experience: 8,
    specialization: ["Economics", "Mathematics"],
    currentlyWorking: true,
  },
];
